### ISSUE TITLE
page 18

### ISSUE THREAD

**Issue by wu526** [netcoreimpl/questions#2]
书中第18页, 
IL_002: stloc.0  解释为从序号为0的本地变量取出一个值并保存到评价堆栈
IL_003: ldloc.0  解释为从序号为0的本地变量取出一个值并保存到评价堆栈
根据书中解释这两句话的作用应该是一致的，为什么都要执行呢？只执行其中一句不可以吗？希望老师帮我解惑一下，谢谢老师。

**Comment by 303248153** [comment]
这里是编辑错误，请看勘误后的内容：
https://netcoreimpl.github.io/assets/fix/18-1.png
